#!/usr/bin/env python3
"""The stalled-restart runbook hands out a command the guard will accept.

WHY THIS EXISTS
---------------
When the implement stage stalls it posts a runbook telling the maintainer how
to restart it: a table of workflow_dispatch inputs and the equivalent
`gh workflow run` line. That advice is generated by one step, and whether it
WORKS is decided by a completely different step in a different job — the
idempotency guard, which admits a `stalled` stage only at `recorded + 1`.

Nothing tied the two together, and they disagreed. The runbook printed
`iteration=$ITERATION` — the iteration that had just failed — while the guard
wanted that plus one, so the command the pipeline handed out was always
classified as a duplicate dispatch.

The disagreement is invisible from every direction a maintainer looks from:

  * `skip=true` makes each later step's `if: ... skip != 'true'` false, so the
    run does nothing and REPORTS SUCCESS in about eleven seconds.
  * Nothing is posted to the lifecycle issue, so the issue still reads
    "stalled, restart it" after a restart was refused.
  * The run's conclusion is green, so the watchdog has nothing to catch.

Observed on issue #184: run 31596632026 (iteration=1, as the runbook said —
green, no-op) against run 31597726542 (iteration=2 — runs the agent). Gates
1-3 all passed on that file the whole time; they prove shell parses, not that
two steps agree about a number.

WHAT THIS CHECKS
----------------
The full round trip, executing the SHIPPED blocks rather than a copy of them
(gate 5 exists because a copy sat green for weeks while checking a filter
that did not ship):

  1. Run `Mark lifecycle record stalled` against a synthetic spec-meta.json
     and read back what it recorded. The guard compares against this file, so
     the harness must not assume what it holds — that assumption IS the bug
     class. It runs against a real git repo with a local bare remote so the
     step's commit/push path executes instead of being stubbed out.
  2. Run `Report stalled on lifecycle issue` and parse the runbook it wrote.
  3. Feed the runbook's own advice into `Idempotency guard` and require
     `skip=false`.

Step 3 is the point: it asserts the advice is ACCEPTED, not that it matches
some number this file also hardcodes. Either step can be rewritten freely;
the gate only fails when they stop agreeing.

The runbook's `spec_dir` and `issue` are checked the same way, because a
restart command is equally unrunnable if it names the wrong spec.

It ends with MUTATION checks that reintroduce the shipped defect and two
plausible drifts, asserting the suite fails on each. A test that cannot fail
is not a test.

Usage: python3 .github/scripts/verify-stall-restart-runbook.py
Requires: bash, jq, git (all present on ubuntu-latest runners).

On Windows, invoke with `python` — `python3` on PATH is usually the Microsoft
Store stub, which exits 49 without running anything. See wc_shell_harness for
why `bash` on PATH is also probed rather than trusted.
"""
import copy
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wc_shell_harness import (ensure_jq, find_step, resolve_bash, run_step,
                              use_utf8_stdout)

STAGE = ".github/workflows/implement.yml"

MARK_STEP = "Mark lifecycle record stalled"
REPORT_STEP = "Report stalled on lifecycle issue"
GUARD_STEP = "Idempotency guard"

# The iterations a stall can happen at. 1 is the overwhelmingly common case
# (and the one observed on #184); the others guard against a fix that special-
# cases the first iteration instead of incrementing.
SCENARIOS = [1, 2, 4]

SPEC_DIR = "specs/034-e2e-verification-tier"
SLUG = "034-e2e-verification-tier"
ISSUE = "184"
SELF_WORKFLOW = "wing-commander-5-implement.yml"
REPO = "charlesguse/wing-commander"

BASH = None

# `gh` is called for labels before the runbook is composed; under `bash -e` a
# missing binary would kill the step before it writes anything. Only exit
# status matters here — no call site reads gh's output.
GH_STUB = """#!/bin/sh
echo "gh $*" >> "$GH_CALLS"
exit 0
"""


def sh(script, cwd):
    """Run a helper snippet through the same bash the steps get."""
    path = os.path.join(cwd, "_helper.sh")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(script)
    return subprocess.run([BASH, "-e", path.replace("\\", "/")], cwd=cwd,
                          capture_output=True, text=True, encoding="utf-8",
                          errors="replace")


def make_workspace(root, iteration):
    """A git repo with a working remote, holding a pre-stall spec-meta.json.

    The stall step commits and pushes. Giving it a real bare remote runs that
    path for real; stubbing git would leave the harness asserting against a
    step that never wrote anything.
    """
    work = tempfile.mkdtemp(dir=root)
    remote = os.path.join(work, "remote.git")
    repo = os.path.join(work, "repo")
    setup = f"""
git init --bare -q -b main '{remote}'
git clone -q '{remote}' '{repo}'
cd '{repo}'
git config user.email harness@example.invalid
git config user.name harness
mkdir -p '{SPEC_DIR}'
printf '%s\\n' '{{"issue": {ISSUE}, "spec_dir": "{SPEC_DIR}", "stage": "implement", "iteration": {iteration}}}' > '{SPEC_DIR}/spec-meta.json'
git add -A
git commit -q -m seed
git push -q origin main
"""
    proc = sh(setup, work)
    if proc.returncode != 0:
        sys.exit(f"::error::harness could not build a git workspace: "
                 f"{proc.stdout}{proc.stderr}")
    return work, repo


def parse_runbook(text):
    """The three dispatch inputs, read from BOTH forms the runbook prints.

    The table and the gh line are written from separate echoes, so a fix
    applied to one and not the other is a live possibility — returning both
    lets the caller require they agree.
    """
    row = re.search(r"\|\s*`iteration`\s*\|\s*`([^`]*)`\s*\|", text)
    cmd = re.search(r"gh workflow run\s+(\S+).*?-f\s+spec_dir=(\S+)\s+"
                    r"-f\s+issue=(\S+)\s+-f\s+iteration=(\S+)", text)
    return {
        "table_iteration": row.group(1) if row else None,
        "workflow": cmd.group(1) if cmd else None,
        "spec_dir": cmd.group(2) if cmd else None,
        "issue": cmd.group(3) if cmd else None,
        "cmd_iteration": cmd.group(4) if cmd else None,
    }


def scenario(steps, iteration, root):
    """One stall-then-restart round trip. Returns a list of failures."""
    failures = []
    where = f"iteration {iteration}"
    work, repo = make_workspace(root, iteration)
    runner_temp = os.path.join(work, "runner_temp")
    bindir = os.path.join(work, "bin")
    calls = os.path.join(work, "gh_calls")
    os.makedirs(runner_temp, exist_ok=True)
    os.makedirs(bindir, exist_ok=True)
    open(calls, "w").close()
    with open(os.path.join(bindir, "gh"), "w", encoding="utf-8",
              newline="\n") as fh:
        fh.write(GH_STUB)
    os.chmod(os.path.join(bindir, "gh"), 0o755)

    # 1. What the stall actually records. The guard reads this file, so the
    #    harness reads it too rather than assuming the stall leaves it alone.
    rc, out, _, _ = run_step(
        BASH, steps[MARK_STEP], repo,
        {"SPEC_DIR": SPEC_DIR, "SLUG": SLUG, "BOT_SLUG": "wing-commander-bot",
         "ITERATION": str(iteration)},
        runner_temp)
    if rc != 0:
        failures.append(f"{where}: {MARK_STEP!r} exited {rc}: {out.strip()}")
        return failures
    with open(os.path.join(repo, SPEC_DIR, "spec-meta.json"),
              encoding="utf-8") as fh:
        meta = json.load(fh)
    if meta.get("stage") != "stalled":
        failures.append(f"{where}: {MARK_STEP!r} left stage="
                        f"{meta.get('stage')!r}, not 'stalled' — the guard's "
                        f"stalled branch cannot be reached at all.")
        return failures
    recorded = meta.get("iteration")

    # 2. The runbook the maintainer is told to follow.
    stall_md = os.path.join(work, "stall-comment.md")
    sh("rm -f /tmp/stall-comment.md", work)
    rc, out, _, _ = run_step(
        BASH, steps[REPORT_STEP], repo,
        {"GH_TOKEN": "x", "ISSUE": ISSUE, "ITERATION": str(iteration),
         "SPEC_DIR": SPEC_DIR, "TIER": "claude-opus-5",
         "REASON": "the retry's agent step itself finished 'failure'",
         "AGENT_MSG": "You've hit your session limit",
         "SELF_WORKFLOW": SELF_WORKFLOW, "RUN_URL": "https://example.invalid/r",
         "GITHUB_REPOSITORY": REPO, "GH_CALLS": calls,
         "PATH": bindir + os.pathsep + os.environ["PATH"]},
        runner_temp)
    if rc != 0:
        failures.append(f"{where}: {REPORT_STEP!r} exited {rc}: {out.strip()}")
        return failures
    if sh(f"cp /tmp/stall-comment.md '{stall_md}'", work).returncode != 0:
        failures.append(f"{where}: {REPORT_STEP!r} wrote no runbook to "
                        f"/tmp/stall-comment.md.")
        return failures
    with open(stall_md, encoding="utf-8") as fh:
        advice = parse_runbook(fh.read())

    missing = [k for k, v in advice.items() if v is None]
    if missing:
        failures.append(
            f"{where}: the runbook no longer states {', '.join(missing)} in "
            f"the form this gate reads. If it was reformatted, update "
            f"parse_runbook — do not drop the check, or the restart command "
            f"goes back to being unverified.")
        return failures

    # The two renderings are written by separate echoes; a fix to one only is
    # exactly the shape of the defect this gate exists for.
    if advice["table_iteration"] != advice["cmd_iteration"]:
        failures.append(
            f"{where}: the runbook's inputs table says iteration="
            f"{advice['table_iteration']} but its gh command says "
            f"{advice['cmd_iteration']} — whichever the maintainer copies, "
            f"one of them is wrong.")

    for key, want in (("spec_dir", SPEC_DIR), ("issue", ISSUE),
                      ("workflow", SELF_WORKFLOW)):
        if advice[key] != want:
            failures.append(f"{where}: runbook {key}={advice[key]!r}, "
                            f"expected {want!r} — the command names the wrong "
                            f"target and cannot restart this spec.")

    # 3. The verdict that matters: does the guard let that advice through?
    for label, value in (("inputs table", advice["table_iteration"]),
                         ("gh command", advice["cmd_iteration"])):
        if not re.fullmatch(r"-?\d+", value or ""):
            failures.append(f"{where}: runbook's {label} iteration "
                            f"{value!r} is not an integer; the guard's "
                            f"`-eq` cannot compare it.")
            continue
        rc, out, outputs, summary = run_step(
            BASH, steps[GUARD_STEP], repo,
            {"STAGE": "stalled", "RECORDED": str(recorded), "ITERATION": value},
            runner_temp)
        if rc != 0:
            failures.append(f"{where}: {GUARD_STEP!r} exited {rc}: "
                            f"{out.strip()}")
            continue
        if outputs.get("skip") != "false":
            failures.append(
                f"{where}: the runbook's {label} tells the maintainer to "
                f"dispatch iteration={value}, but the guard refuses it "
                f"(skip={outputs.get('skip')!r}) against the "
                f"stage='stalled', iteration={recorded} the stall just "
                f"recorded. The restart is swallowed as a duplicate and the "
                f"run reports SUCCESS having done nothing. Guard said: "
                f"{summary.strip() or '(no summary)'}")
    return failures


def suite(steps, root):
    return [f for it in SCENARIOS for f in scenario(steps, it, root)]


def load_steps():
    return {name: find_step(STAGE, name)["run"]
            for name in (MARK_STEP, REPORT_STEP, GUARD_STEP)}


def _mut_runbook_prints_failed_iteration(steps):
    """The shipped defect: advise the iteration that just failed."""
    steps[REPORT_STEP] = steps[REPORT_STEP].replace(
        "$restart_iteration", "$ITERATION")


def _mut_guard_wants_two_ahead(steps):
    """Drift on the guard side rather than the runbook side."""
    steps[GUARD_STEP] = steps[GUARD_STEP].replace(
        "next=$((RECORDED + 1))", "next=$((RECORDED + 2))")


def _mut_stall_resets_recorded_iteration(steps):
    """The stall commit stops preserving the iteration the guard compares to."""
    steps[MARK_STEP] = steps[MARK_STEP].replace(
        """jq '.stage = "stalled"'""", """jq '.stage = "stalled" | .iteration = 0'""")


MUTATIONS = [
    ("runbook advises the iteration that just failed",
     _mut_runbook_prints_failed_iteration),
    ("guard admits only recorded+2", _mut_guard_wants_two_ahead),
    ("stall commit resets the recorded iteration",
     _mut_stall_resets_recorded_iteration),
]


def main():
    global BASH
    use_utf8_stdout()
    ensure_jq()
    BASH = resolve_bash()
    if not shutil.which("git"):
        sys.exit("::error::git is not on PATH. The shipped step under test "
                 "commits and pushes, so nothing here can run without it.")

    steps = load_steps()
    root = tempfile.mkdtemp()
    try:
        failures = suite(steps, root)
        for f in failures:
            print(f"::error::{f}")

        for label, apply_mutation in MUTATIONS:
            mutated = copy.deepcopy(steps)
            apply_mutation(mutated)
            if mutated == steps:
                print(f"::error::mutation {label!r} changed nothing — the code "
                      f"it edits was rewritten. Update the mutation so this "
                      f"harness keeps proving it can fail.")
                failures.append(f"mutation inapplicable: {label}")
                continue
            if suite(mutated, root):
                print(f"Mutation OK — {label}: caught.")
            else:
                print(f"::error::MUTATION SURVIVED — reintroducing {label} "
                      f"broke nothing in this suite, so the suite is not "
                      f"testing that defect. Fix the scenarios, not the "
                      f"mutation.")
                failures.append(f"mutation survived: {label}")
    finally:
        shutil.rmtree(root, ignore_errors=True)

    print(f"stall restart runbook: {len(SCENARIOS)} round trip(s), "
          f"{len(MUTATIONS)} mutation(s); {len(failures)} failure(s).")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
